name:
version:             0.1.0.0
github:              "githubuser/hi"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hi#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
#- -Wall
#- -Werror
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - megaparsec
    - prettyprinter
    - prettyprinter-ansi-terminal
    - scientific
    - haskeline
    - mtl
    - text
    - parser-combinators
    - containers

executables:
  hi:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hi
    - haskeline

tests:
  hi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hi
    - prettyprinter
    - hspec
    - text
    - megaparsec
    - template-haskell
    - QuickCheck
    - containers